### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by komuw** [komuw/wiji-benchmarks#1]
1. adder
```sh
workers_1        | {'event': 'wiji.Worker.consume_tasks', 'stage': 'start', 'task_name': 'AdderTask', 'queue_name': 'AdderTaskQueue', 'worker_id': 'A48NCEM68NGQUIR2S', 'process_id': 1}
workers_1        | {'event': 'wiji.SimpleRateLimiter.limit', 'stage': 'start', 'task_name': 'AdderTask', 'queue_name': 'AdderTaskQueue', 'worker_id': 'A48NCEM68NGQUIR2S', 'process_id': 1}
workers_1        | {'event': 'wiji.Worker.run_task', 'stage': 'end', 'state': 'task execution error', 'error': "run() missing 2 required positional arguments: 'a' and 'b'", 'task_name': 'AdderTask', 'queue_name': 'AdderTaskQueue', 'worker_id': 'A48NCEM68NGQUIR2S', 'process_id': 1}
workers_1        | Traceback (most recent call last):
workers_1        |   File "/usr/local/lib/python3.7/site-packages/wiji/worker.py", line 183, in run_task
workers_1        |     return_value = await self.the_task.run(*task_args, **task_kwargs)
workers_1        | TypeError: run() missing 2 required positional arguments: 'a' and 'b'
workers_1        | {'event': 'wiji.SimpleRateLimiter.execution_outcome', 'stage': 'end', 'state': 'execution_outcome record', 'task_name': 'AdderTask', 'task_id': 'oz4hynzp2mx9y', 'queue_name': 'AdderTaskQueue', 'execution_duration': {'thread_time': 0.0011, 'perf_counter': 0.0011, 'monotonic': 0.0011, 'process_time': 0.0012}, 'execution_exception': "run() missing 2 required positional arguments: 'a' and 'b'", 'return_value': 'None', 'worker_id': 'A48NCEM68NGQUIR2S', 'process_id': 1}
```

2. divider
```sh
workers_1        | {'event': 'wiji.Worker.consume_tasks', 'stage': 'start', 'task_name': 'DividerTask', 'queue_name': 'DividerTaskQueue', 'worker_id': 'HYXIJ4NYA8RSE8SXD', 'process_id': 1}
workers_1        | {'event': 'wiji.SimpleRateLimiter.limit', 'stage': 'start', 'task_name': 'DividerTask', 'queue_name': 'DividerTaskQueue', 'worker_id': 'HYXIJ4NYA8RSE8SXD', 'process_id': 1}
workers_1        | {'event': 'wiji.Worker.run_task', 'stage': 'end', 'state': 'task execution error', 'error': "run() missing 1 required positional argument: 'dividend'", 'task_name': 'DividerTask', 'queue_name': 'DividerTaskQueue', 'worker_id': 'HYXIJ4NYA8RSE8SXD', 'process_id': 1}
workers_1        | Traceback (most recent call last):
workers_1        |   File "/usr/local/lib/python3.7/site-packages/wiji/worker.py", line 183, in run_task
workers_1        |     return_value = await self.the_task.run(*task_args, **task_kwargs)
workers_1        | TypeError: run() missing 1 required positional argument: 'dividend'
workers_1        | {'event': 'wiji.SimpleRateLimiter.execution_outcome', 'stage': 'end', 'state': 'execution_outcome record', 'task_name': 'DividerTask', 'task_id': 'ld48lbj71unjj', 'queue_name': 'DividerTaskQueue', 'execution_duration': {'thread_time': 0.0007, 'perf_counter': 0.0007, 'monotonic': 0.0007, 'process_time': 0.0007}, 'execution_exception': "run() missing 1 required positional argument: 'dividend'", 'return_value': 'None', 'worker_id': 'HYXIJ4NYA8RSE8SXD', 'process_id': 1}
```

3. disk io
```sh
workers_1        | {'event': 'wiji.SimpleRateLimiter.limit', 'stage': 'start', 'task_name': 'DiskIOTask', 'queue_name': 'DiskIOTaskQueue', 'worker_id': 'ZYGM6CQF5AFO9L99C', 'process_id': 1}
workers_1        | {'event': 'wiji.Worker.run_task', 'stage': 'end', 'state': 'task execution error', 'error': "run() missing 1 required positional argument: 'filename'", 'task_name': 'DiskIOTask', 'queue_name': 'DiskIOTaskQueue', 'worker_id': 'ZYGM6CQF5AFO9L99C', 'process_id': 1}
workers_1        | Traceback (most recent call last):
workers_1        |   File "/usr/local/lib/python3.7/site-packages/wiji/worker.py", line 183, in run_task
workers_1        |     return_value = await self.the_task.run(*task_args, **task_kwargs)
workers_1        | TypeError: run() missing 1 required positional argument: 'filename'
workers_1        | {'event': 'wiji.SimpleRateLimiter.execution_outcome', 'stage': 'end', 'state': 'execution_outcome record', 'task_name': 'DiskIOTask', 'task_id': 'nsx31ywr0o8hr', 'queue_name': 'DiskIOTaskQueue', 'execution_duration': {'thread_time': 0.0011, 'perf_counter': 0.0012, 'monotonic': 0.0009, 'process_time': 0.0009}, 'execution_exception': "run() missing 1 required positional argument: 'filename'", 'return_value': 'None', 'worker_id': 'ZYGM6CQF5AFO9L99C', 'process_id': 1}
```

4. disk io(**weird**)
```sh
workers_1        | {'event': 'wiji.SimpleRateLimiter.execution_outcome', 'stage': 'end', 'state': 'execution_outcome record', 'task_name': 'DiskIOTask', 'task_id': 'nsx31ywr0o8hr', 'queue_name': 'DiskIOTaskQueue', 'execution_duration': {'thread_time': 0.001, 'perf_counter': 0.0011, 'monotonic': 0.0011, 'process_time': 0.0012}, 'execution_exception': "run() missing 1 required positional argument: 'filename'", 'return_value': 'None', 'worker_id': 'ZYGM6CQF5AFO9L99C', 'process_id': 1}
```

5. even weird, some tasks are succeding(adder task); maybe the errors are happening when we consume something bogus from SQS
```sh
workers_1        | {'event': 'wiji.Worker.consume_tasks', 'stage': 'start', 'task_name': 'AdderTask', 'queue_name': 'AdderTaskQueue', 'worker_id': 'A48NCEM68NGQUIR2S', 'process_id': 1}
workers_1        | {'event': 'wiji.SimpleRateLimiter.limit', 'stage': 'start', 'task_name': 'AdderTask', 'queue_name': 'AdderTaskQueue', 'worker_id': 'A48NCEM68NGQUIR2S', 'process_id': 1}
workers_1        | {'event': 'wiji.SimpleRateLimiter.execution_outcome', 'stage': 'end', 'state': 'execution_outcome record', 'task_name': 'AdderTask', 'task_id': 'oz4hynzp2mx9y', 'queue_name': 'AdderTaskQueue', 'execution_duration': {'thread_time': 0.0011, 'perf_counter': 0.0011, 'monotonic': 0.0011, 'process_time': 0.0011}, 'execution_exception': 'None', 'return_value': '178', 'worker_id': 'A48NCEM68NGQUIR2S', 'process_id': 1}
```

added: https://github.com/komuw/wiji-benchmarks/blob/master/benchmarks/myHook.py#L36-L42 to catch it in the act

**Comment by komuw** [comment]
caused by; https://github.com/komuw/wijisqs/issues/29

**Comment by komuw** [comment]
closed by; https://github.com/komuw/wijisqs/pull/30
